import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Providers as HeroProvider } from '~/client/providers/HeroProvider'
import { SWRProvider } from '~/client/providers/SWRProvider'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Snooze App',
  description: 'Generated by Edison.Cheung'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ padding: 0, margin: 0 }}
      >
        <HeroProvider>
          <SWRProvider>{children}</SWRProvider>
        </HeroProvider>
      </body>
    </html>
  )
}
