import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from '~/client/components/Toaster'
import { ChakraUIProvider } from '~/client/providers/ChakraUIProvider'
import { SWRProvider } from '~/client/providers/SWRProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Snooze App',
  description: 'Generated by Edison.Cheung'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ padding: 0, margin: 0 }}
      >
        <ChakraUIProvider>
          <SWRProvider>
            {children}
            <Toaster />
          </SWRProvider>
        </ChakraUIProvider>
      </body>
    </html>
  )
}
